name: talk-desktop
adopt-info: talk-desktop
summary: A snap for the Nextcloud Talk Desktop Client
description: |
  A desktop client for Nextcloud Talk, providing chat, video, and audio call functionality.
  This snap packages the talk-desktop application for easy installation on Linux distributions.

base: core24
grade: stable
confinement: strict
compression: lzo

license: AGPL-3.0
issues: https://github.com/kz6fittycent/talk-desktop/issues
source-code: https://github.com/nextcloud/talk-desktop
website: https://github.com/nextcloud/talk-desktop
icon: snap/gui/icon.png

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

apps:
  talk-desktop:
    command: usr/local/bin/Nextcloud_Talk
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - network
      - audio-playback
      - audio-record
      - camera
      - wayland
      - x11
    environment:
      DISABLE_WAYLAND: "1"
      ELECTRON_LOGGING: "1"

parts:
  talk-desktop:
    plugin: nil
    source: https://github.com/nextcloud/talk-desktop
    source-type: git
    build-packages:
      - wget
      - unzip
        
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"
           
    override-build: |   
      # Get latest release from Nextcloud Repo
      wget https://github.com/nextcloud-releases/talk-desktop/releases/latest/download/Nextcloud.Talk-linux-x64.zip
      unzip Nextcloud.Talk-linux-x64.zip
      mkdir -p $CRAFT_PART_INSTALL/usr/local/bin/
      chown -R root:root Nextcloud\ Talk-linux-x64/ 
      chmod -R 4755 Nextcloud\ Talk-linux-x64/ 
      cd Nextcloud\ Talk-linux-x64/   
      mv Nextcloud\ Talk Nextcloud_Talk 
      chmod +x Nextcloud_Talk
      cp -r * $CRAFT_PART_INSTALL/usr/local/bin/
      
